import React, { useContext, useEffect, useState } from "react";

import { PiMicrosoftExcelLogo } from "react-icons/pi";

import "./TransactionHeader.css";
import FinanceContext from "../../../Contexts/FinanceContext/FinanceContext";
import { utils, writeFileXLSX } from "xlsx";
import { convertToPersianDate } from "../../../utils/formatDate.js";

const TransactionHeader = ({ search, categoryName, trxType, setFilters }) => {
  const { category, transaction } = useContext(FinanceContext);
  const searchTransactionHandler = (e) => {
    setFilters((prev) => ({ ...prev, search: e.target.value }));
  };
  const filterTransactionHandler = (e) => {
    setFilters((prev) => ({ ...prev, categoryName: e.target.value }));
  };
  const trxTypeHandler = (e) => {
    setFilters((prev) => ({ ...prev, trxType: e.target.value }));
  };

  //this function generated by AI
  const exportExcelHandler = () => {
    // ۱. نگاشت داده‌ها به عناوین فارسی
    const formattedData = transaction?.map((item) => ({
      "عنوان تراکنش": item.title,
      تاریخ: convertToPersianDate(item.created_at),
      "نوع تراکنش": item.trx_type === "e" ? "هزینه" : "درآمد",
      "مبلغ (تومان)": item.amount,
      توضیحات: item.note,
    }));

    // ۲. ساخت Worksheet از روی داده‌ها
    const worksheet = utils.json_to_sheet(formattedData);

    // ۳. راست‌چین کردن شیت (RTL) برای زبان فارسی
    if (!worksheet["!views"]) worksheet["!views"] = [];
    worksheet["!views"].push({ RTL: true });

    // ۴. تنظیم عرض ستون‌ها
    worksheet["!cols"] = [
      { wch: 15 }, // شناسه
      { wch: 12 }, // تاریخ
      { wch: 12 }, // نوع
      { wch: 15 }, // مبلغ
      { wch: 25 }, // توضیحات
    ];
    // ۵. ساخت Workbook و افزودن Worksheet
    const workbook = utils.book_new();
    utils.book_append_sheet(workbook, worksheet, "تراکنش‌ها");

    // ۶. دانلود فایل اکسل
    writeFileXLSX(workbook, "Transactions_Report.xlsx");
  };
  return (
    <div className="table__header">
      <div className="table__header-right">
        <input
          value={search}
          onChange={searchTransactionHandler}
          className="table__header-search"
          type="text"
          placeholder={`جستجو...`}
        />
        <select
          className="table__header-select"
          value={categoryName}
          onChange={filterTransactionHandler}
        >
          <option value="all">همه دسته بندی ها</option>
          {category?.map((cat) => {
            return (
              <option key={cat.id} value={cat.id}>
                {cat.name}
              </option>
            );
          })}
        </select>
        <select
          className="table__header-select"
          value={trxType}
          onChange={trxTypeHandler}
        >
          <option value="">نوع تراکنش ها</option>
          <option value="i">درآمد</option>
          <option value="e">هزینه</option>
        </select>
      </div>
      <div className="table__header-left">
        <button className="table__header-excel" onClick={exportExcelHandler}>
          خروجی اکسل <PiMicrosoftExcelLogo />
        </button>
      </div>
    </div>
  );
};

export default TransactionHeader;
