import "./ReportLineChart.css";
import React from "react";
import {
  AreaChart,
  Area,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  Legend,
  ResponsiveContainer,
} from "recharts";

//this component generated by AI
const ReportLineChart = ({ data }) => {
  if (!data || data.length === 0) {
    return (
      <div
        style={{
          padding: "40px",
          textAlign: "center",
          color: "var(--color-text-3, #888)",
        }}
      >
        تراکنشی در این بازه زمانی ثبت نشده است.
      </div>
    );
  }

  return (
    <div style={{ width: "100%", height: "350px", minHeight: "300px" }}>
      <ResponsiveContainer width="100%" height="100%">
        <AreaChart
          data={data}
          margin={{ top: 10, right: 10, left: 10, bottom: 5 }}
        >
          {/* تعریف گرادینت‌های رنگی زیر خطوط */}
          <defs>
            {/* گرادینت برای درآمد (سبز) */}
            <linearGradient id="colorIncome" x1="0" y1="0" x2="0" y2="1">
              <stop offset="5%" stopColor="#22c55e" stopOpacity={0.4} />
              <stop offset="95%" stopColor="#22c55e" stopOpacity={0.0} />
            </linearGradient>

            {/* گرادینت برای هزینه (قرمز) */}
            <linearGradient id="colorExpense" x1="0" y1="0" x2="0" y2="1">
              <stop offset="5%" stopColor="#ef4444" stopOpacity={0.4} />
              <stop offset="95%" stopColor="#ef4444" stopOpacity={0.0} />
            </linearGradient>
          </defs>

          <CartesianGrid strokeDasharray="3 3" opacity={0.3} />
          <XAxis
            dataKey="name"
            stroke="var(--color-text-3, #666)"
            fontSize={11}
          />
          <YAxis
            width="auto"
            stroke="var(--color-text-3, #666)"
            fontSize={11}
          />

          {/* تنظیمات Tooltip با پس‌زمینه کاملاً کدر و بدون شفافیت */}
          <Tooltip
            cursor={{
              stroke: "var(--color-border-2, #ccc)",
              strokeDasharray: "3 3",
            }}
            contentStyle={{
              backgroundColor: "#1e293b", // پس‌زمینه کدر و غیرشفاف (تیره/مقاوم)
              borderColor: "var(--color-border-2, #334155)",
              borderRadius: "8px",
              color: "#ffffff",
              boxShadow: "0 10px 15px -3px rgba(0, 0, 0, 0.3)",
              opacity: 1, // کاملا غیرشفاف
            }}
            itemStyle={{ color: "#ffffff" }}
          />

          <Legend />

          {/* منطقه و خط درآمد */}
          <Area
            name="درآمد"
            type="monotone"
            dataKey="income"
            stroke="#22c55e"
            strokeWidth={2}
            fillOpacity={1}
            fill="url(#colorIncome)"
            dot={{ r: 4, fill: "#22c55e" }}
            activeDot={{ r: 7 }}
          />

          {/* منطقه و خط هزینه */}
          <Area
            name="هزینه"
            type="monotone"
            dataKey="expense"
            stroke="#ef4444"
            strokeWidth={2}
            fillOpacity={1}
            fill="url(#colorExpense)"
            dot={{ r: 4, fill: "#ef4444" }}
            activeDot={{ r: 7 }}
          />
        </AreaChart>
      </ResponsiveContainer>
    </div>
  );
};

export default ReportLineChart;
