// hooks/usePeriod.js
import { useContext, useMemo } from "react";
import FinanceContext from "../Contexts/FinanceContext/FinanceContext";

//this hook generated by AI
const usePeriod = (selectedPeriod) => {
  const { transaction = [] } = useContext(FinanceContext);

  const chartData = useMemo(() => {
    if (!transaction || transaction.length === 0) return [];

    const now = new Date();

    // ۱. فیلتر کردن تراکنش‌ها بر اساس بازه زمانی
    const filteredTransactions = transaction.filter((trx) => {
      if (!trx.created_at) return false;

      const trxDate = new Date(trx.created_at);
      if (isNaN(trxDate.getTime())) return false;

      const diffInMs = now.getTime() - trxDate.getTime();

      if (selectedPeriod === "daily") {
        return (
          trxDate.getDate() === now.getDate() &&
          trxDate.getMonth() === now.getMonth() &&
          trxDate.getFullYear() === now.getFullYear()
        );
      }

      if (selectedPeriod === "weekly") {
        const SEVEN_DAYS_IN_MS = 7 * 24 * 60 * 60 * 1000;
        return diffInMs >= 0 && diffInMs <= SEVEN_DAYS_IN_MS;
      }

      if (selectedPeriod === "monthly") {
        const THIRTY_DAYS_IN_MS = 30 * 24 * 60 * 60 * 1000;
        return diffInMs >= 0 && diffInMs <= THIRTY_DAYS_IN_MS;
      }

      return true; // حالت 'all'
    });

    // ۲. نگاشت تک‌تک تراکنش‌ها برای چارت
    const formattedData = filteredTransactions.map((trx, index) => {
      const trxDate = new Date(trx.created_at);

      const dateStr = trxDate.toLocaleDateString("fa-IR", {
        month: "2-digit",
        day: "2-digit",
      });
      const timeStr = trxDate.toLocaleTimeString("fa-IR", {
        hour: "2-digit",
        minute: "2-digit",
      });

      const labelName =
        selectedPeriod === "daily" ? timeStr : `${dateStr} - ${timeStr}`;
      const rawAmount = Number(trx.amount) || 0;

      // تشخیص نوع تراکنش: e = هزینه | i = درآمد
      const isExpense = trx.trx_type === "e";

      return {
        id: trx.id || index,
        name: labelName,
        income: isExpense ? 0 : Math.abs(rawAmount),
        expense: isExpense ? Math.abs(rawAmount) : 0,
        rawDate: trxDate,
      };
    });

    // ۳. مرتب‌سازی صعودی بر اساس زمان
    return formattedData.sort((a, b) => a.rawDate - b.rawDate);
  }, [transaction, selectedPeriod]);

  return { chartData };
};

export default usePeriod;
