//This Code generated by AI
import { format, parseISO } from "date-fns-jalali";

export const convertToPersianDate = (isoString) => {
  if (!isoString) return "";

  try {
    // ۱. تبدیل رشته متنی به شیء تاریخ در جاوااسکریپت
    const date = parseISO(isoString);

    // ۲. فرمت کردن تاریخ به صورت شمسی و جمع‌وجور (مثال: ۱۴۰۵/۰۴/۲۶)
    return format(date, "yyyy/MM/dd");
  } catch (error) {
    console.error("خطا در تبدیل تاریخ:", error);
    return isoString; // در صورت بروز خطا، همان تاریخ اصلی را برمی‌گرداند تا برنامه خراب نشود
  }
};
